### ISSUE TITLE
Internal server error on 1.7.10

### ISSUE THREAD

**Issue by JamiePhonic** [Pokefenn/Chisel#74]
an internal occurs on 1.7.10 Cauldron servers if you attempt to use the chisel while NOT looking at a block.
If you right click in the air the GUI opens, but attempting to select anyting in your inventory to put in it causes this:

`
Console : [20:30:37 WARN]: Failed to handle packet for /192.168.0.2
Console : java.lang.IndexOutOfBoundsException: Index: 53, Size: 45
Console :   at java.util.ArrayList.rangeCheck(ArrayList.java:635) ~[?:1.7.0_71]
Console :   at java.util.ArrayList.get(ArrayList.java:411) ~[?:1.7.0_71]
Console :   at net.minecraft.inventory.Container.func_75144_a(Container.java:383) ~[zs.class:?]
Console :   at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2041) ~[nh.class:?]
Console :   at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
Console :   at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
Console :   at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
Console :   at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
Console :   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
Console :   at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
Console :   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
Console :   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
Console :   at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Console : [20:30:37 INFO]: Player lost connection: Internal server error
`

**Comment by JamiePhonic** [comment]
Issue is gone in cauldron patch 207.
