### ISSUE TITLE
game keeps crashing!!! What do I do?

### ISSUE THREAD

**Issue by OJTheGaming** [Pokefenn/Chisel#88]
I've been trying to play mc but it keeps crashing with this mod Idk why but I really tried to fix it myself but I can't It was working when I took decocraft out but I've used decocraft and this mod many times together but now its a problem, I keep getting these types of crashes because one is not compatible with one but I used both side by side in the past but now its a problem. I really hope I can figure this out soon. 

crash report: 
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 9/7/19 10:49 AM
Description: Registering texture

net.minecraft.client.renderer.StitcherException: Unable to fit: Chisel:iron/terrain-iron-largeingot-top - size: 16x16 - Maybe try a lowerresolution resourcepack?
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:76)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:260)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:97)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:172)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:76)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:260)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:97)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/atlas/blocks.png
	Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:172)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 442343416 bytes (421 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	AppleCore{1.3.9} [AppleCore] (AppleCore-mc1.7.10-1.3.9.jar) 
	UCHIJA	BetterFoliage{2.0.14} [Better Foliage] (Better-Foliage-Mod-1.7.10.jar) 
	UCHIJA	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) 
	UCHIJA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks.jar) 
	UCHIJA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCHIJA	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) 
	UCHIJA	BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJA	CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJA	CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(19jun17).jar) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (DecoCraft-Mod-1.7.10 (5).jar) 
	UCHIJA	props{2.4.1} [Decocraft] (DecoCraft-Mod-1.7.10 (5).jar) 
	UCHIJA	fairylights{1.4.0} [Fairy Lights] (Fairy-Lights-Mod-1.7.10.jar) 
	UCHIJA	flowercraftmod{1.9} [Flowercraft] (Flowercraft-Mod-1.7.10.jar) 
	UCHIJA	GardenContainers{1.7.10-1.7.0} [Garden Containers] (Garden-Stuff-Mod-1.7.10.jar) 
	UCHIJA	GardenCore{1.7.10-1.7.0} [Garden Core] (Garden-Stuff-Mod-1.7.10.jar) 
	UCHIJA	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (Garden-Stuff-Mod-1.7.10.jar) 
	UCHIJA	GardenTrees{1.7.10-1.7.0} [Garden Trees] (Garden-Stuff-Mod-1.7.10.jar) 
	UCHIJA	HungerInPeace{1.0.0} [Hunger In Peace] (HungerInPeace-mc1.7.10-1.0.0.jar) 
	UCHIJA	LotsOfFood{1.7.10} [Lots of Food] (Lots of Food-1.7.10 v7.jar) 
	UCHIJA	malisiscore{1.7.10-0.14.3} [MalisisCore] (MalisisCore-1.7.10.jar) 
	UCHIJA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJA	moreplayermodels{1.7.10} [MorePlayerModels] (MorePlayerModels_1.7.10 (1).jar) 
	UCHIJA	musiccraft{2.9.9.3} [MusicCraft] (musiccraft-2.9.9.3.jar) 
	UCHIJA	secretroomsmod{@VERSION@} [The SecretRoomsMod] (Secret-Rooms-Mod-1.7.10.jar) 
	UCHIJA	securitycraft{v1.8.2.1} [SecurityCraft] (SecurityCraft-Mod-1.7.10.jar) 
	UCHIJA	soggytransportation{4.5.0} [SoggyMustache's Transportation] (soggytransportation-4.5.0(1.7.10).jar) 
	UCHIJA	tropicraft{v6.0.5} [Tropicraft] (tropicraft-6.0.5.jar) 
	UCHIJA	aziasvendingmachine{1.0.1} [Vending Machines Revamped] (Vending-Machines-Revamped-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13476 Compatibility Profile Context 22.19.180.1536' Renderer: 'AMD Radeon R7 Graphics'
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon R7 Graphics GL version 4.5.13476 Compatibility Profile Context 22.19.180.1536, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by OJTheGaming** [comment]
can somebody please help me
